on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch master
        run: git fetch origin master
      - name: Validate
        run: ./bin/validate-version.sh
