name: Validate

on:
  check_run:
    types: [rerequested, requested_action]
    
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: ./bin/validate-version.sh
